### ISSUE TITLE
tweet = entry["content"]["item"]["content"]["tweet"]

### ISSUE THREAD

**Issue by Scrapehouse** [lschmelzeisen/nasty#13]
Hey everybody and thank you for this great tool.

However, I'm facing a strange issue (tested on CentOS 7 as well as MacOS):

` nasty search --query "(from:realdonaldtrump)" --since 2020-10-06 --until 2020-10-07 --filter LATEST --max-tweets -1`

leads to this error message:

Traceback (most recent call last):
  File "/usr/local/bin/nasty", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/nasty/__main__.py", line 25, in main
    NastyProgram.init(*args).run()
  File "/usr/local/lib/python3.6/site-packages/nasty/_cli.py", line 113, in run
    for tweet in request.request():
  File "/usr/local/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 66, in __next__
    if not self._update_callback():
  File "/usr/local/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 209, in _update_tweet_stream
    batch = self._fetch_batch()
  File "/usr/local/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 352, in _fetch_batch
    self._session_get(**self._batch_url()).json()
  File "/usr/local/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 76, in __init__
    self.tweets: Final = self._tweets()
  File "/usr/local/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 90, in _tweets
    for tweet_id in self._tweet_ids():
  File "/usr/local/lib/python3.6/site-packages/nasty/_retriever/search_retriever.py", line 122, in _tweet_ids
    tweet = entry["content"]["item"]["content"]["tweet"]
KeyError: 'tweet'

What makes me wonder is the fact, that other dates and accounts are working fine. 

Is there any solution to this problem?

Thank you.

**Comment by lschmelzeisen** [comment]
Thanks for reporting this!

It turns out there was only a single offending Tweet: [1313449844413992961](https://twitter.com/realDonaldTrump/status/1313449844413992961). In this case, Twitter decided to hide the Tweet content behind a "tombstone", but still keep it accessible.

This sould be fixed in the newly published version 0.2.7.
