### ISSUE TITLE
Unable to run the progam

### ISSUE THREAD

**Issue by feedmari** [lschmelzeisen/nasty#2]
Hello,
I'm trying to run the program as specified in the README but I'm getting the following error:

Issued command:  
`nasty search --query "climate change"`

Results:
```
Traceback (most recent call last):
  File "/Users/fcks/anaconda3/envs/vui/bin/nasty", line 8, in <module>
    sys.exit(main())
  File "/Users/fcks/anaconda3/envs/vui/lib/python3.6/site-packages/nasty/cli/main.py", line 52, in main
    command.run()
  File "/Users/fcks/anaconda3/envs/vui/lib/python3.6/site-packages/nasty/cli/_request_command.py", line 104, in run
    for tweet in request.request():
  File "/Users/fcks/anaconda3/envs/vui/lib/python3.6/site-packages/nasty/request/search.py", line 146, in request
    return SearchRetriever(self).tweet_stream
  File "/Users/fcks/anaconda3/envs/vui/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 175, in __init__
    self._fetch_new_twitter_session()
  File "/Users/fcks/anaconda3/envs/vui/lib/python3.6/site-packages/nasty/_retriever/retriever.py", line 321, in _fetch_new_twitter_session
    )[0]
IndexError: list index out of range
```

Do you have any ideas about why is this happening?

**Comment by lschmelzeisen** [comment]
Hi @feedmari

Sorry for taking so long to respond to this. The error you describe happened because of an oversight of using the [overrides](https://pypi.org/project/overrides/)-package with dunder methods, that only materialized in Python 3.7+ and not in my dev environment 3.6. I just pushed out an updated version that should fix this and added configuration for automatically running the tests against all supported Python versions.

I'm closing this as I'm relatively sure this if fixed. So, please try again. Reopen, if the problem continues.

Additionally, if you don't mind me asking, how did you hear about this project?

**Comment by feedmari** [comment]
Hi @lschmelzeisen 

Thanks for the quick fix, I confirm now it's working!

I don't remember where I found this repo, usually I use github hashtags!
